// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "flutter_background_geolocation",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "flutter-background-geolocation",
            targets: ["flutter_background_geolocation"]
        )
    ],
    dependencies: [
        // Generated by the Flutter tool alongside this package (SPM builds only;
        // requires Flutter >= 3.38 — matches the pubspec environment floor).
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        .package(url: "https://github.com/transistorsoft/native-background-geolocation.git", from: "4.5.0"),
        .package(url: "https://github.com/transistorsoft/transistor-background-fetch.git", from: "4.0.5")
    ],
    targets: [
        .target(
            name: "flutter_background_geolocation",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(name: "BackgroundGeolocation", package: "native-background-geolocation"),
                .product(name: "TSBackgroundFetch", package: "transistor-background-fetch")
            ],
            cSettings: [
                .headerSearchPath("include/flutter_background_geolocation")
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedLibrary("sqlite3")
                // .linkedLibrary("c++")  // only if you truly need it
            ]
        )
    ]
)
