name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request.
  - type: checkboxes
    id: terms
    attributes:
      label: Required Reading
      description: I have read the following Wikis [Philosophy of Operation](../wiki/Philosophy-of-Operation) and [Debugging](../wiki/Debugging).  I am aware of the [API Documentation](https://pub.dev/documentation/flutter_background_geolocation/latest/)
      options:
        - label: Confirmed
          required: true
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: What version of our software are you running?
      placeholder: Consult your pubspec.yaml
    validations:
      required: true
  - type: textarea
    id: doctor
    attributes:
      label: Flutter Doctor
      description: "Execute `$ flutter doctor` and provide the output here."
      placeholder: "$ flutter doctor"
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Mobile operating-system(s)
      description: Which mobile operating-system(s) is this issue reported upon?
      options:
        - label: iOS
        - label: Android
  - type: input
    id: device-info
    attributes:
      label: Device Manufacturer(s) and Model(s)
      description: What is the device model(s) and manufacturer(s)
      placeholder: eg Google Pixel 6, iPhone 13 Pro
    validations:
      required: true
  - type: input
    id: device-os
    attributes:
      label: Device operating-systems(s)
      description: Affected device operating system
      placeholder: eg iOS 18.1, Android 13
    validations: 
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true  
  - type: textarea
    id: config
    attributes:
      label: Plugin Code and/or Config
      description: Provide the Config you're using with the `BackgroundGeolocation.ready(config)` method along with any other relevant code.
      placeholder: "Paste your Config or code here, eg: BackgroundGeolocation.ready(config).\n\nYour code will be automatically syntax-highlighted"
      render: dart
    validations:
      required: true  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "include iOS / Android logs\n- $ adb logcat -s TSLocationManager:V\n- ios XCode logs\n- Logs from BackgroundGeolocation.emailLog(address)"
      render: shell

