#!/bin/sh

adb shell "run-as com.transistorsoft.flutterbackgroundgeolocationexample cat /data/user/0/com.transistorsoft.flutterbackgroundgeolocationexample/databases/transistor_log.db" > transistor_log.db

